name: Error Report (Automated)
description: Report an error captured by LENR Academy's error reporting system
title: "[Error]: "
labels: ["bug", "needs-triage", "automated-report"]
body:
  - type: markdown
    attributes:
      value: |
        ## Automated Error Report

        This template is designed for errors reported through LENR Academy's built-in error reporting system.

        **If you clicked "Report This Error" in the app:** Simply paste the error details from your clipboard below in the "Error Report" field.

        **If you're manually creating this report:** Please use the [Bug Report](https://github.com/Episk-pos/lenr.academy/issues/new?template=bug_report.yml) template instead, which provides structured fields for manual entry.

  - type: textarea
    id: error-report
    attributes:
      label: Error Report
      description: |
        Paste the complete error report that was copied to your clipboard when you clicked "Report This Error".

        The report should include:
        - Error fingerprint
        - Error type and message
        - Stack trace
        - Browser/OS/device information
        - URL and timestamp
        - Steps to reproduce (please fill these in)
      placeholder: |
        Paste the automated error report here...

        After pasting, please scroll down to the "Steps to Reproduce" section
        and fill in the steps that led to this error.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this error hasn't been reported already (check for the error fingerprint)
          required: true
        - label: I have pasted the complete error report from the clipboard
          required: true
        - label: I have filled in the "Steps to Reproduce" section in the error report above
          required: true
        - label: I have tested this on the latest version at https://lenr.academy
          required: true
