name: Feature Request
description: Propose a new feature or enhancement for LENR Academy
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please ensure your request aligns with LENR Academy's core mission: providing interactive tools for exploring Low Energy Nuclear Reactions and cold fusion transmutation pathways based on Dr. Alexander Parkhomov's nuclear reaction tables.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - Query Enhancement (fusion/fission/two-to-two filters or results)
        - Data Visualization (charts, graphs, periodic table improvements)
        - Element/Nuclide Explorer (ShowElementData enhancements)
        - User Experience (UI/UX, navigation, accessibility)
        - Performance (loading, caching, query speed)
        - Data Export/Import (CSV, JSON, sharing)
        - Documentation (help text, tutorials, explanations)
        - New Query Type (entirely new reaction search capability)
        - Other (please specify in Description)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What problem does this feature solve? What use case or workflow is currently difficult or impossible?
        A clear problem statement helps us understand the "why" behind your request.
      placeholder: |
        Currently, when I try to..., I find it difficult because...
        As a researcher/student/educator, I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Describe your ideal solution. Be as specific as possible about UI elements, interactions, and expected behavior.
      placeholder: |
        I would like to see...
        The feature should work like this:
        1. User does X
        2. System responds with Y
        3. Result is Z
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Have you considered any alternative solutions or workarounds? What are the trade-offs?
      placeholder: |
        I've tried..., but it doesn't work well because...
        Another approach could be..., but...
    validations:
      required: false

  - type: dropdown
    id: alignment
    attributes:
      label: Project Vision Alignment
      description: |
        Does this feature align with LENR Academy's core mission of exploring nuclear transmutation pathways?
      options:
        - "Yes - Directly supports nuclear reaction exploration"
        - "Yes - Improves data accessibility and understanding"
        - "Yes - Enhances educational value"
        - "Partially - Related but tangential"
        - "Unsure - Need feedback"
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope and Complexity
      description: |
        Help us understand the scope:
        - Is this a small UI tweak or a major new capability?
        - Does it require new database tables/columns?
        - Does it affect existing functionality?
        - Should it work on mobile, desktop, or both?
      placeholder: |
        This would primarily affect...
        It should work on mobile/desktop/both...
        It may require changes to...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples and References
      description: |
        Do you have examples from other applications, mockups, or reference materials?
        Links to similar features elsewhere can be very helpful.
      placeholder: |
        Similar to how [App X] does it: https://...
        Mockup: [attach image or link]
        Academic paper explaining the need: https://...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to you?
      options:
        - Critical - Blocks my primary workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have, would use regularly
        - Low - Minor improvement, occasional use
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: |
        Who would benefit from this feature? How would it improve the LENR Academy experience?
      placeholder: |
        This would help researchers who...
        Students could use this to...
        It would make it easier to discover...
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
          required: false
        - label: I can provide detailed specifications or test cases
          required: false
        - label: I can help test and provide feedback during development
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been requested already
          required: true
        - label: This feature aligns with LENR Academy's mission of exploring nuclear transmutation pathways
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: This feature is unambiguous and clearly defined
          required: true
