name: E2E Tests (PR)

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Create test database
        run: |
          # For CI, we need a minimal database file or mock
          # Since the 207MB database is too large for CI, we'll let tests handle it
          # The tests should work with the actual download or use mocked data
          echo "Database will be downloaded during test execution"

      - name: Run Playwright tests (Chromium only for PRs)
        run: npx playwright test --project=chromium
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: test-results/
          retention-days: 7
